version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/keys/:/etc/nginx/keys
      - nginx_cache:/var/cache/nginx
    deploy:
      resources:
        reservations:
          cpus: "4"
          memory: "4G"
volumes:
  nginx_cache:
