version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_cache:/var/cache/nginx
volumes:
  nginx_cache:
